#
# MAINTAINER        Joson
# DOCKER-VERSION    1.0.0
#
# Dockerizing Mariadb: Dockerfile for building Mariadb images
#
# docker build -t pq784844602/mariadb .
#
# docker run --name mysql -v /usr/local/mysql/data:/var/lib/mysql -d pq784844602/mariadb
#
# docker exec -it mysql bash
#
FROM mariadb

MAINTAINER Joson

ENV MYSQL_ROOT_PASSWORD Baipeng2016
ENV TZ=Asia/Shanghai

EXPOSE 3306
	